services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/ping/

  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.4
    container_name: redis

  postgres:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
# volumes:
#   database:
